### ISSUE TITLE
YouTube link for Kickoff is last year

### ISSUE THREAD

**Issue by indcoder** [virtualmlnet/hackathon-2021#2]
Please check the YouTube link for the kickoff meeting in the readme; it looks to be pointing to last year kickoff. The Twitch link is fine

**Comment by luisquintanilla** [comment]
Thanks @indcoder, updating once the stream is scheduled. Stay tuned 🙂

**Comment by indcoder** [comment]
You can create a  Live Event with a future date in YouTube. This will allow folks to subscribe and get notified when the Live Event starts. This will improve your visitor count. Infact the Twitch link does it

**Comment by virtualmlnet** [comment]
Hi @indcoder,

Links have been updated. You'll find the in the READM, but for convenience I've included them here as well.

[YouTube (UK/Australia)](https://www.youtube.com/watch?v=7cLMwtDa0S4) / [YouTube US](https://www.youtube.com/watch?v=NofGYVdL49o)
